### ISSUE TITLE
Move ftp to daemon (not shim)

### ISSUE THREAD

**Issue by illusionyy** [astrelsky/libhijacker#6]
FTP doesn't like rest mode much and after waking up from rest mode, it no longer responds to request from the client and it can't be killed until user restarts the system.

Elf loader still works, daemon just gets killed when you wake up from rest mode and can be sent again.

**Comment by astrelsky** [comment]
The ftp server is in the shim because I can't terminate it on command and so that changes can be made to the filesystem for testing without having to put code in the daemon for creating files and stuff, which is why I added it in the first place.


I'd like to argue that neither the daemon or the shim are friendly with rest mode they just aren't logging errors. I was not aware that anything actually ran in rest mode. The entire process should be suspended and then resumed after exiting rest mode. I need to figure out how to do this.

**Comment by illusionyy** [comment]
They were suspended when entering rest mode  (no logs, no connections) but I wasn't sure if ftp not responding after rest mode was the intended behavior.

**Comment by illusionyy** [comment]
Turns out ftp server was the one spamming accept messages after waking from rest mode.
![image](https://github.com/astrelsky/libhijacker/assets/37698908/3039b26c-ee9e-4bd9-bd4f-29c609f3bfaa)

**Comment by astrelsky** [comment]
Noted

**Comment by nirav99254** [comment]
Getting below error, can someone help?

```
Nirav-MacbookPro:libhijacker nirav$ python3 ./send_elf.py 192.168.0.110
/Users/nirav/Desktop/Nirav/libhijacker/./send_elf.py: start
has_daemon: False
start send_spawner(args)
Traceback (most recent call last):
  File "/Users/nirav/Desktop/Nirav/libhijacker/./send_elf.py", line 375, in <module>
    main()
  File "/Users/nirav/Desktop/Nirav/libhijacker/./send_elf.py", line 369, in main
    asyncio.run(run_loggers(args))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/nirav/Desktop/Nirav/libhijacker/./send_elf.py", line 295, in run_loggers
    await send_spawner(args)
  File "/Users/nirav/Desktop/Nirav/libhijacker/./send_elf.py", line 268, in send_spawner
    await logger_client(args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/Users/nirav/Desktop/Nirav/libhijacker/./send_elf.py", line 170, in open_connection
    await writer.drain()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 366, in drain
    raise exc
  File "/Users/nirav/Desktop/Nirav/libhijacker/./send_elf.py", line 166, in open_connection
    yield reader, writer
  File "/Users/nirav/Desktop/Nirav/libhijacker/./send_elf.py", line 254, in logger_client
    await writer.drain()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 378, in drain
    await self._protocol._drain_helper()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/streams.py", line 173, in _drain_helper
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/selector_events.py", line 1082, in _write_ready
    n = self._sock.send(self._buffer)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

```

**Comment by astrelsky** [comment]
> Getting below error, can someone help?
> 
> - snip -

If you are getting this after issuing a keyboard interrupt you can just ignore it.

**Comment by nirav99254** [comment]
> > Getting below error, can someone help?
> > 
> > * snip -
> 
> If you are getting this after issuing a keyboard interrupt you can just ignore it.

But nothing happens after this `Broken Pipe` line. Also I am not sure what do you mean by "keyboard interrupt".

**Comment by illusionyy** [comment]
I remember the script doesn't work on unix without some small changes to ignore the broken pipe

**Comment by nirav99254** [comment]
<img width="188" alt="Screenshot 2023-08-27 at 9 50 15 PM" src="https://github.com/astrelsky/libhijacker/assets/1610634/ba9bcacc-35b3-4f64-abe1-1c0297f51e2d">

On my PS5 i get this message once broken pipe is printed on my Macbook Pro Terminal.

**Comment by astrelsky** [comment]
> I remember the script doesn't work on unix without some small changes to ignore the broken pipe

I wasn't aware of this. What change is needed?

**Comment by illusionyy** [comment]
Maybe it works at least on Linux now. was getting broken pipe on my WSL Ubuntu installation.

**Comment by astrelsky** [comment]
Resolved in [HEN-V](https://github.com/astrelsky/HEN-V)
